tosca_definitions_version: tosca_simple_yaml_1_1
description: Demo service for OpenStack deployment

topology_template:

  node_templates:

    network12:
      type: Network

    server1:
      type: Server
      requirements:
        - virtual_network:
            node: network12
            capability: virtual_network
        - security_group:
            node: network12
            capability: security_group
        - resource_group:
            node: network12
            capability: resource_group

    server2:
      type: Server
      requirements:
        - virtual_network:
            node: network12
            capability: virtual_network
        - security_group:
            node: network12
            capability: security_group
        - resource_group:
            node: network12
            capability: resource_group